-- =====================================================================
-- schema.sql  --  Tabellen der Datenbank (PostgreSQL / Supabase)
-- ---------------------------------------------------------------------
-- In Supabase einmalig im SQL-Editor ausfuehren (oder lokal via psql).
-- Spaltennamen/-typen entsprechen exakt den JPA-Entities.
-- =====================================================================

DROP TABLE IF EXISTS auftrag_arbeitstyp CASCADE;
DROP TABLE IF EXISTS auftrag CASCADE;
DROP TABLE IF EXISTS benutzer CASCADE;
DROP TABLE IF EXISTS kunde CASCADE;

-- Kunde -----------------------------------------------------------------
CREATE TABLE kunde (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(100) NOT NULL,
    strasse VARCHAR(100),
    plz     VARCHAR(10),
    ort     VARCHAR(60),
    telefon VARCHAR(20),
    natel   VARCHAR(20)
);

-- Benutzer --------------------------------------------------------------
CREATE TABLE benutzer (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    benutzername VARCHAR(50) NOT NULL UNIQUE,
    passwort     VARCHAR(255),
    name         VARCHAR(100),
    rolle        VARCHAR(20) NOT NULL  -- ADMIN | BEREICHSLEITER | MITARBEITER
);

-- Auftrag ---------------------------------------------------------------
CREATE TABLE auftrag (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    datum            DATE,
    zeit             TIME,
    status           VARCHAR(20) NOT NULL, -- ERFASST | DISPONIERT | AUSGEFUEHRT | FREIGEGEBEN | VERRECHNET
    beschreibung     VARCHAR(500),
    terminwunsch     VARCHAR(100),
    objekt_adresse   VARCHAR(150),
    geplanter_termin DATE,
    rapport_text     VARCHAR(1000),
    erstellt_am      TIMESTAMP,
    kunde_id         BIGINT REFERENCES kunde(id),
    benutzer_id      BIGINT REFERENCES benutzer(id)   -- zugewiesener Mitarbeiter
);

-- Zwischentabelle Auftrag <-> Arbeitstyp (n:m) --------------------------
CREATE TABLE auftrag_arbeitstyp (
    auftrag_id BIGINT NOT NULL REFERENCES auftrag(id),
    arbeitstyp VARCHAR(20) NOT NULL,  -- REPARATUR | SANITAER | HEIZUNG | GARANTIE
    PRIMARY KEY (auftrag_id, arbeitstyp)
);
